cask_args appdir: "/Applications"

# Common formulas
brew "watch"
brew "zsh-syntax-highlighting"
brew "eza"
brew "bat"
brew "fzf"
brew "fd"
brew "zoxide"
brew "git-delta"
brew "stow"
brew "lnav"
brew "procs"
brew "starship"
brew "fnm"
cask "font-hack-nerd-font"

if RUBY_PLATFORM =~ /linux/
  brew "atlassian/homebrew-acli/acli"
end

if RUBY_PLATFORM =~ /darwin/
  brew "tmux" # tmux is already installed in codespaces
  brew "awscli"
  brew "ffmpeg"
  brew "gh"
  brew "uv"
  brew "k9s"
  brew "redis"
  brew "httpie"
  brew "yq"
  brew "jq"
  brew "mysql"
  brew "ripgrep"
  brew "tree"
  brew "tailscale"
  
  brew "FelixKratz/formulae/borders"
  brew "felixkratz/formulae/sketchybar"

  # casks
  cask "google-chrome"
  cask "sublime-text"
  cask "webstorm"
  cask "spotify"
  # cask "iterm2"
  cask "zoom"
  cask "slack"
  # cask "penc"
  cask "obsidian"
  cask "postman"
  cask "raycast"
  cask "obs"
  cask "visual-studio-code"
  cask "1password"
  cask "1password/tap/1password-cli"
  cask "notion"
  cask "vlc"
  cask "nikitabobko/tap/aerospace"
  cask "ghostty"
  cask "arc"
  cask "superwhisper"
end

