#!/usr/bin/env zsh

DIR=$(cd `dirname $0` && pwd)

function configure_screenshot_storage(){
	# Setup the screenshots directory and have the OS store all screenshots there
	[ ! -d ~/screenshots ] && mkdir ~/screenshots
	defaults write com.apple.screencapture location ~/screenshots
	defaults write com.apple.screencapture "show-thumbnail" -bool "false" 
	killall SystemUIServer
}

function configure_dock_settings(){
	defaults write com.apple.dock "autohide" -bool "true"
	defaults write com.apple.dock "orientation" -string "left"
	defaults write com.apple.dock expose-group-apps -bool true
	killall Dock
}

function configure_finder() {
	defaults write com.apple.finder "ShowPathbar" -bool "true" && killall Finder
}

function setup_tmux() {
	mkdir -p ~/.tmux/plugins
	clone_tmux_plugin_manager
}

function clone_tmux_plugin_manager(){
	[ -d ~/.tmux/plugins/tpm ] && return
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

### Oh My Zsh
function setup_oh_my_zsh_plugins() {
	custom_plugins_dir="${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins"
	[ -d "$custom_plugins_dir" ] || mkdir -p "$custom_plugins_dir"

	
	# fzf zsh plugin
	fzf_zsh_plugin_dir="${custom_plugins_dir}/fzf-zsh-plugin"
	[ -d "$fzf_zsh_plugin_dir" ] || git clone --depth 1 https://github.com/unixorn/fzf-zsh-plugin.git "$fzf_zsh_plugin_dir"

	# fzf-tab
	fzf_tab_dir="${custom_plugins_dir}/fzf-tab"
	[ -d "$fzf_tab_dir" ] || git clone https://github.com/Aloxaf/fzf-tab "$fzf_tab_dir"
	
	# fzf git plugin
	fzf_git_plugin_dir="${custom_plugins_dir}/fzf-git-plugin"
	[ -d "$fzf_git_plugin_dir" ] || git clone https://github.com/junegunn/fzf-git.sh.git "$fzf_git_plugin_dir"
	
	# yarn completions	
	zsh_yarn_completions_dir="${custom_plugins_dir}/zsh-yarn-completions"
	[ -d "$zsh_yarn_completions_dir" ] || git clone https://github.com/chrisands/zsh-yarn-completions "$zsh_yarn_completions_dir"
}

function setup_oh_my_zsh() {
	if [ -d ~/.oh-my-zsh ]; then
			echo "Oh my zsh is already installed"
	else
	  echo "Installing Oh My Zsh..."
		sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	fi
	mkdir -p ~/.zsh/completions
	setup_oh_my_zsh_plugins
}

### end Oh My Zsh

function install_homebrew_for_linux(){
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	sudo apt-get install build-essential
	eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
	(cd $DIR/brew && brew bundle install)
	gh extension install dlvhdr/gh-dash

}



### apt packages
function install_apt_packages() {
	sudo apt-get update
}

### end apt packages

function install_npm_globals() {
	# npm i -g  @anthropic-ai/claude-code
}


setup_tmux


if [[ $OSTYPE == 'darwin'* ]]; then
	stow -t "$HOME" aerospace
  echo -ne "Updating MacOS UI config...\033[0K\r"
  configure_screenshot_storage
  configure_dock_settings
  configure_finder
  echo -e "Updating MacOS UI config... Done"
fi

if [[ $OSTYPE == 'linux-gnu'* ]]; then
	echo -ne "Installing homebrew...\033[0K\r"
	install_homebrew_for_linux
	echo -ne "Installing apt packages...\033[0K\r"
	install_apt_packages
	echo -e "Installing apt packages... Done"
	mkdir -p ~/.fzf/shell
	ln -s  /usr/share/doc/fzf/examples/key-bindings.zsh ~/.fzf/shell/key-bindings.zsh
	
fi


echo "Symlinking dotfiles..."

# if ~/.zshrc exists, delete it
[ -f ~/.zshrc ] && rm ~/.zshrc

./stow.sh
./bin/.local/bin/setup-efs
setup_oh_my_zsh


# make sure default shell is set to zsh
sudo chsh -s $(which zsh) $USERNAME


echo "Configuring shell..."
source ~/.zshrc
echo "Done."

