set -g status-interval 5
set -g status-right '#(echo "$CDE_DISPLAY_NAME") #(~/.local/bin/svc-health -u http://127.0.0.1:8081/health -n web -t 500) #{?pane_current_path,#{pane_current_path},} #[fg=#{@catppuccin_blue}]#[fg=#{@catppuccin_base} bg=#{@catppuccin_blue}]#{@pane_current_path} #[default]'

# pop ups

# web log viewer 
bind C-l display-popup -w "90%" -h "80%" -E "zsh -lic 'logs_lnav web'" 
